"""init

Revision ID: 0ceacb0facc8
Revises:
Create Date: 2026-03-15 10:57:30.676229

"""

import typing

import sqlalchemy

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0ceacb0facc8"
down_revision: typing.Union[str, None] = None
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sqlalchemy.Column("shard", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("kind", sqlalchemy.String(length=256), nullable=False),
        sqlalchemy.Column("title", sqlalchemy.String(length=8192), nullable=True),
        sqlalchemy.Column("created", sqlalchemy.DateTime(timezone=True), nullable=False),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_shard"), "chat", ["shard"], unique=False)
    op.create_table(
        "file",
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("storage", sqlalchemy.String(length=256), nullable=False),
        sqlalchemy.Column("bucket", sqlalchemy.String(length=1024), nullable=False),
        sqlalchemy.Column("key", sqlalchemy.String(length=8192), nullable=False),
        sqlalchemy.Column("filename", sqlalchemy.String(length=8192), nullable=True),
        sqlalchemy.Column("content_type", sqlalchemy.String(length=1024), nullable=True),
        sqlalchemy.Column("size_bytes", sqlalchemy.BigInteger(), nullable=True),
        sqlalchemy.Column("created", sqlalchemy.DateTime(timezone=True), nullable=False),
        sqlalchemy.PrimaryKeyConstraint("id"),
        sqlalchemy.UniqueConstraint("bucket", "key", name="uq_files_bucket_key"),
    )
    op.create_index(op.f("ix_file_bucket"), "file", ["bucket"], unique=False)
    op.create_index(op.f("ix_file_key"), "file", ["key"], unique=False)
    op.create_table(
        "member",
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("chat_id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("user_id", sqlalchemy.String(length=256), nullable=False),
        sqlalchemy.Column("created", sqlalchemy.DateTime(timezone=True), nullable=False),
        sqlalchemy.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sqlalchemy.PrimaryKeyConstraint("id"),
        sqlalchemy.UniqueConstraint("chat_id", "user_id", name="uq_member_chat_user"),
    )
    op.create_index(op.f("ix_member_chat_id"), "member", ["chat_id"], unique=False)
    op.create_index(op.f("ix_member_user_id"), "member", ["user_id"], unique=False)
    op.create_table(
        "message",
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("chat_id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("member_id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("body", sqlalchemy.String(length=16384), nullable=True),
        sqlalchemy.Column("created", sqlalchemy.DateTime(timezone=True), nullable=True),
        sqlalchemy.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sqlalchemy.ForeignKeyConstraint(["member_id"], ["member.id"], ondelete="CASCADE"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_chat_id"), "message", ["chat_id"], unique=False)
    op.create_index(op.f("ix_message_member_id"), "message", ["member_id"], unique=False)
    op.create_table(
        "message_file",
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("message_id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("file_id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("position", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("created", sqlalchemy.DateTime(timezone=True), nullable=False),
        sqlalchemy.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sqlalchemy.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_file_file_id"), "message_file", ["file_id"], unique=False)
    op.create_index(op.f("ix_message_file_message_id"), "message_file", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_file_message_id"), table_name="message_file")
    op.drop_index(op.f("ix_message_file_file_id"), table_name="message_file")
    op.drop_table("message_file")
    op.drop_index(op.f("ix_message_member_id"), table_name="message")
    op.drop_index(op.f("ix_message_chat_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_member_user_id"), table_name="member")
    op.drop_index(op.f("ix_member_chat_id"), table_name="member")
    op.drop_table("member")
    op.drop_index(op.f("ix_file_key"), table_name="file")
    op.drop_index(op.f("ix_file_bucket"), table_name="file")
    op.drop_table("file")
    op.drop_index(op.f("ix_chat_shard"), table_name="chat")
    op.drop_table("chat")
    # ### end Alembic commands ###
