"""init

Revision ID: ca2ff557716e
Revises:
Create Date: 2026-03-17 20:02:46.146272

"""

import typing

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "ca2ff557716e"
down_revision: typing.Union[str, None] = None
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=2048), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("topic", sa.String(length=2048), nullable=False),
        sa.Column("priority", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=16384), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("path", sa.String(length=8192), nullable=False),
        sa.Column("filename", sa.String(length=8192), nullable=False),
        sa.Column("content_type", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=2048), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("authorization", sa.DateTime(timezone=True), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "member",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("role_id", sa.String(length=256), nullable=False),
        sa.Column("position", sa.BigInteger(), nullable=True),
        sa.Column("notifications", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=True),
        sa.Column("member_id", sa.String(length=256), nullable=True),
        sa.Column("kind", sa.String(length=256), nullable=False),
        sa.Column("text", sa.String(length=16384), nullable=True),
        sa.Column("pinned", sa.DateTime(timezone=True), nullable=True),
        sa.Column("edited", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["member.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attachment",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=False),
        sa.Column("file_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forward",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=False),
        sa.Column("source_message_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "read",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=False),
        sa.Column("member_id", sa.String(length=256), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["member_id"], ["member.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reply",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=False),
        sa.Column("source_message_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reply")
    op.drop_table("read")
    op.drop_table("forward")
    op.drop_table("attachment")
    op.drop_table("message")
    op.drop_table("member")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_table("file")
    op.drop_table("event")
    op.drop_table("chat")
    # ### end Alembic commands ###
